FROM node:20-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
RUN corepack enable pnpm
ARG TEMPLATE_PATH
COPY ${TEMPLATE_PATH}/package.json ${TEMPLATE_PATH}/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app
RUN corepack enable pnpm
ARG TEMPLATE_PATH
COPY --from=deps /app/node_modules ./node_modules
COPY ${TEMPLATE_PATH}/ ./
ENV NODE_ENV=production
RUN pnpm build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN corepack enable pnpm
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["pnpm", "start"]
